### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by tujger** [eclipsesource/jsonforms#1516] opened 2019-11-05 15:37 UTC
After updating to the last version, I get when server starts:

```
C:/pantheon/workspace14/JSONForms/node_modules/@jsonforms/react/lib/DispatchCell.d.ts
TypeScript error in C:/pantheon/workspace14/JSONForms/node_modules/@jsonforms/react/lib/DispatchCell.d.ts(9,58):
Namespace '"C:/pantheon/workspace14/JSONForms/node_modules/@types/react-redux/index"' has no exported member 'ConnectedComponentClass'.  TS2694

     7 |     render(): JSX.Element;
     8 | }
  >  9 | export declare const DispatchCell: import("react-redux").ConnectedComponentClass<typeof Dispatch, Pick<DispatchCellProps, never> & OwnPropsOfCell>;
       |                                                          ^
    10 | export {};
```

**Screenshots**
![image](https://user-images.githubusercontent.com/12112326/68221792-fe2d7200-ffb7-11e9-9f69-3c2e2b2792bf.png)

**Used Setup:**
 - OS: Windows
 - IDE/Text Editor: Idea
 - Framework: react
 - RendererSet: material

**Additional context**
```
dependencies": {
    "@jsonforms/core": "^2.3.1",
    "@jsonforms/examples": "^2.3.1",
    "@jsonforms/material-renderers": "^2.3.1",
    "@jsonforms/react": "^2.3.1",
    "@material-ui/core": "^4.3.3",
    "@material-ui/icons": "^4.2.1",
    "brace": "^0.11.1",
    "font-awesome": "^4.7.0",
    "material-ui-dropzone": "^2.4.5",
    "primeicons": "^2.0.0",
    "primereact": "^3.3.2",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-ace": "^8.0.0",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.0",
    "react-redux": "^6.0.0",
    "react-select": "^3.0.8",
    "react-swipeable-views": "^0.13.3",
    "styled-components": "^4.2.0",
    "typescript": "^3.6.4"
  },
```

**Comment by sdirix** [comment] 2019-11-05 16:41
Thanks for the bug report. We'll take a look soon.

**Comment by sdirix** [comment] 2019-11-12 11:04
Can you try updating your `react-redux`, and or `types/react-redux:`? For further guidance I'll need to know the actual versions of the packages you have installed, so you'll need to share your `package-lock.json` file.

**Comment by tujger** [comment] 2019-11-12 12:37
Updates with, but the same error. Packege-lock.json is attached.
[package-lock.zip](https://github.com/eclipsesource/jsonforms/files/3836136/package-lock.zip)

**Comment by sdirix** [comment] 2019-11-12 19:40
Thanks. I was now able to reproduce the issue. I was able to fix it locally for me by fixing the version of the react redux types to `1.7.2` via `"@types/react-redux": "1.7.2"`. You had `7.1.5` installed which seems to be incompatible to the types we used to build our last release.

**Comment by sdirix** [comment] 2019-11-12 19:41
Please confirm whether that fixes the issue for you. I'll keep this issue open for other people encountering this problem and to fix this for the next release.

**Comment by tujger** [comment] 2019-11-12 19:55
Hmmm.
`
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/react-redux@1.7.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'JSONForms'
npm ERR! notarget
`

**Comment by sdirix** [comment] 2019-11-12 21:19
Sorry I meant `7.1.2` and mistyped ;)

**Comment by tujger** [comment] 2019-11-12 21:35
Have installed @types/react-redux@7.1.2 and react-redux@7.1.2

Got:

     {path}/JSONForms/node_modules/react-scripts/lib/react-app.d.ts
     TypeScript error in {path}/JSONForms/node_modules/react-scripts/lib/react-app.d.ts(3,23):
     Cannot find type definition file for 'react-dom'.  TS2688

         1 | /// <reference types="node" />
         2 | /// <reference types="react" />
       > 3 | /// <reference types="react-dom" />
           |                       ^
         4 | 
         5 | declare namespace NodeJS {
         6 |   interface ProcessEnv {

There is: "react-dom": "^16.8.6"

Sorry :)

**Comment by sdirix** [comment] 2019-11-12 21:52
That's fine. I would try installing "@types/react-dom".

**Comment by tujger** [comment] 2019-11-13 16:49
Thank you. It seems, it finally passes the compilation without that issues. There are other type mismatches but i'm sure it can be solved.

**Comment by tujger** [comment] 2019-11-13 18:55
I'm not sure, may be it is happen due to stricter types definition in recent updates? I added my own components, and now most of them throws something like this:

`
TypeScript error in .../JSONForms/src/controls/FileBrowserControl.tsx(19,10):
Type '{ cells?: { tester: RankedTester; cell: any; }[] | undefined; label: string | Labels | (string & {}) | (string & ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<...>)> | null) | (new (props: any)
 => Component<...>)>) | ... 8 more ... | (Labels & ReactPortal...' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Component<(Pick<unknown, never> & OwnPropsOfControl) | (Pick<Pick<unknown, never> & OwnPropsOfControl, "visible" | "ena
bled" | "path" | "id" | "schema" | "uischema" | "renderers"> & Pick<...>) | (Pick<...> & ... 1 more ... & Partial<...>) | (Pick<...> & ... 1 more ... ...'.
  Type '{ cells?: { tester: RankedTester; cell: any; }[] | undefined; label: string | Labels | (string & {}) | (string & ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<...>)> | null) | (new (props: an
y) => Component<...>)>) | ... 8 more ... | (Labels & ReactPortal...' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Component<(Pick<unknown, never> & OwnPropsOfControl) | (Pick<Pick<unknown, never> & OwnPropsOfControl, "visible" | "e
nabled" | "path" | "id" | "schema" | "uischema" | "renderers"> & Pick<...>) | (Pick<...> & ... 1 more ... & Partial<...>) | (Pick<...> & ... 1 more ... ...'.
    Type '{ cells?: { tester: RankedTester; cell: any; }[] | undefined; label: string | Labels | (string & {}) | (string & ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<...>)> | null) | (new (props:
any) => Component<...>)>) | ... 8 more ... | (Labels & ReactPortal...' is not assignable to type 'IntrinsicClassAttributes<Component<(Pick<unknown, never> & OwnPropsOfControl) | (Pick<Pick<unknown, never> & OwnPropsOfControl, "visible" | "enabled" | "path" | "i
d" | "schema" | "uischema" | "renderers"> & Pick<...>) | (Pick<...> & ... 1 more ... & Partial<...>) | (Pick<...> & ... 1 more ... & Partial<...>), any, a...'.
      Types of property 'ref' are incompatible.
`

**Comment by sdirix** [comment] 2019-11-14 17:00
Can you share your custom control? If not something reproducible which throws the same type errors? I would like to look at that in more detail.

**Comment by tujger** [comment] 2019-11-14 18:56
Here are two controls:

IconButtonControl.tsx:

`
import React from 'react';
import {connect} from 'react-redux';
import {mapStateToControlProps, StatePropsOfControl} from '@jsonforms/core';
import {ButtonControl} from "./index";
import {ButtonProps} from "@material-ui/core/Button";

const IconButtonControl = function (props: ButtonProps & StatePropsOfControl) {
    const {uischema = {} as any} = props;
    const {options = {} as any} = uischema;
    options.hideLabel = true;

    return (
        <ButtonControl
            {...props}
        />
    );
};

const ConnectedMaterialIconButtonControl = connect(mapStateToControlProps)(IconButtonControl);
export default ConnectedMaterialIconButtonControl;
`

And ButtonControl.tsx:

`import React from 'react';
import {connect} from 'react-redux';
import {mapStateToControlProps, StatePropsOfControl} from '@jsonforms/core';
import {Button, Icon, Tooltip} from '@material-ui/core';
import {ButtonProps} from "@material-ui/core/Button";
import "font-awesome/css/font-awesome.css";

// import {Button} from 'primereact/button';

class ButtonControl extends React.Component<ButtonProps & StatePropsOfControl> {
    containerRef?: any;

    componentDidMount(): void {
        try {
            this.containerRef.current.childrenRef.parentNode.classList.add("wrapped");
        } catch (e) {
            console.error(e);
        }
    }

    render() {
        const {label, uischema, schema, visible, path, id, onClick} = this.props;
        const {text = "", options = {} as any, rule = {} as any} = uischema as any;
        const {hideLabel = false, rightIcon = null, rightIconClass = null} = options;
        const {effect = null} = rule;

        this.containerRef = React.createRef();
        const xlabel = label as string | undefined;

        let faIcon = null;
        if (rightIcon) {
            const tokens = rightIcon.match(/class="(fa fa-.*?)"/);
            if (tokens && tokens.length > 1) {
                faIcon = tokens[1];
            }
        }

        return <Tooltip title={label || text} innerRef={this.containerRef}>
            <div><Button
                id={id}
                disabled={effect === "DISABLE"}
                onClick={onClick || (() => {
                    console.log("onClick -> " + path)
                })}
                style={((hideLabel || !label) && !rightIcon) ? {display: "none"} : {whiteSpace: "nowrap"}}
                variant="contained">
                    {hideLabel ? "" : xlabel || ""}
                {
                    faIcon && <Icon className={faIcon} fontSize={"inherit"}/>
                }
            </Button></div>
        </Tooltip>
    }
}

const ConnectedMaterialButtonControl = connect(mapStateToControlProps)(ButtonControl);
export default ConnectedMaterialButtonControl;
`

Produces error:

`.../JSONForms/src/controls/IconButtonControl.tsx
TypeScript error in C:/pantheon/workspace14/JSONForms/src/controls/IconButtonControl.tsx(13,10):
Type '{ action?: ((instance: ButtonBaseActions | null) => void) | RefObject<ButtonBaseActions> | null | undefined; buttonRef?: ((instance: unknown) => void) | RefObject<unknown> | null | undefined; ... 294 more ...; path: string; }' is not assignable to type 'IntrinsicClassAttributes<Component<Pick<{ action?: ((instance: ButtonBaseActions | null) => void) | RefObject<ButtonBaseActions> | null | undefined; buttonRef?: ((instance: unknown) => void) | RefObject<unknown> | null | undefined; ... 7 more ...; TouchRippleProps?: Partial<...> | undefined; } & { ...; } & CommonPro...'.
  Types of property 'ref' are incompatible.
    Type '((instance: HTMLButtonElement | null) => void) | RefObject<HTMLButtonElement> | null | undefined' is not assignable to type 'string | ((instance: Component<Pick<{ action?: ((instance: ButtonBaseActions | null) => void) | RefObject<ButtonBaseActions> | null | undefined; buttonRef?: ((instance: unknown) => void) | RefObject<unknown> | null | undefined; ... 7 more ...; TouchRippleProps?: Partial<...> | undefined; } & { ...; } & CommonProps<....'.
      Type '(instance: HTMLButtonElement | null) => void' is not assignable to type 'string | ((instance: Component<Pick<{ action?: ((instance: ButtonBaseActions | null) => void) | RefObject<ButtonBaseActions> | null | undefined; buttonRef?: ((instance: unknown) => void) | RefObject<unknown> | null | undefined; ... 7 more ...; TouchRippleProps?: Partial<...> | undefined; } & { ...; } & CommonProps<....'.
        Type '(instance: HTMLButtonElement | null) => void' is not assignable to type '(instance: Component<Pick<{ action?: ((instance: ButtonBaseActions | null) => void) | RefObject<ButtonBaseActions> | null | undefined; buttonRef?: ((instance: unknown) => void) | RefObject<unknown> | null | undefined; ... 7 more ...; TouchRippleProps?: Partial<...> | undefined; } & { ...; } & CommonProps<...> & Pick...'.
          Types of parameters 'instance' and 'instance' are incompatible.
            Type 'Component<Pick<{ action?: ((instance: ButtonBaseActions | null) => void) | RefObject<ButtonBaseActions> | null | undefined; buttonRef?: ((instance: unknown) => void) | RefObject<unknown> | null | undefined; ... 7 more ...; TouchRippleProps?: Partial<...> | undefined; } & { ...; } & CommonProps<...> & Pick<...> & Sta...' is not assignable to type 'HTMLButtonElement | null'.
              Type 'Component<Pick<{ action?: ((instance: ButtonBaseActions | null) => void) | RefObject<ButtonBaseActions> | null | undefined; buttonRef?: ((instance: unknown) => void) | RefObject<unknown> | null | undefined; ... 7 more ...; TouchRippleProps?: Partial<...> | undefined; } & { ...; } & CommonProps<...> & Pick<...> & Sta...' is missing the following properties from type 'HTMLButtonElement': autofocus, disabled, form, formAction, and 255 more.  TS2322

    11 | 
    12 |     return (
  > 13 |         <ButtonControl
       |          ^
    14 |             {...props}
    15 |         />
    16 |     );
`

**Comment by sdirix** [comment] 2019-11-22 07:41
While investigating your issue we noticed that with Typescript 3.7 the `cell.ts` throws a compile error [which is fixed now](https://github.com/eclipsesource/jsonforms/pull/1523).

However your problem with the custom controls seems unrelated to JSON Forms. We were able to reproduce the issue, but it seems to originate from the material-ui `ButtonProps`. When using another interface the code compiles. We found no quick fix for that.

**Comment by sdirix** [comment] 2019-11-29 15:20
We updated all dependencies and no longer ran into issues. Can you try again with the latest version of JSON Forms ?

**Comment by tujger** [comment] 2019-12-02 14:42
Getting this on `npm install`
![image](https://user-images.githubusercontent.com/12112326/69968175-df9f9580-14e7-11ea-931e-c982eccfb8cc.png)

Meanwhile, i fixed almost all my issues just replacing the types restrictions with `any`.

**Comment by sdirix** [comment] 2019-12-03 13:42
Hi @tujger, I'm not sure where the error is coming from in your case as all our dependencies to `react-redux` require at most version `^7.1.3`, it's only `@types/react-redux` which requires `^7.1.5`.

**Comment by tujger** [comment] 2019-12-03 13:46
Uh-hu, that is weird, why in my case it happen 7.1.5 in both cases. Suppose, it is my mistake, sorry.

**Comment by sdirix** [comment] 2019-12-08 20:13
I will close this for now. Let me know when you have further problems / questions regarding the typings in JSON Forms.

**Closed by sdirix** 2019-12-08 20:13 UTC
Labels: react
