### ISSUE TITLE
Inconsistent UI state in material number input 

### ISSUE THREAD

**Issue by shivgarg5676** [eclipsesource/jsonforms#1497] opened 2019-09-07 15:22 UTC
Please see the following video link to understand the issue in material number input. Issue happens mainly when you have a trailing `.` in the input, the title overlaps on the text. 
https://drive.google.com/open?id=1xNR9dSaAziwcS9MO4hu2EdE6yhWlS8oi

I know this is a very edge case scenario and most of the users won't face this but It is nice to fix this someday.

**Comment by sdirix** [comment] 2019-09-09 07:35
We welcome any kind of bug report. While this is not app-breaking it still should be fixed of course!

**Comment by LukasBoll** [comment] 2023-10-27 18:10
Unfortunately, the video was removed, since the issue was created in 2019. So, I can´t recreate the issue. I tested the number input with very long inputs and trailing `.` in angular material and MUI and wasn´t able to overlap textfield/input and title.

**Comment by sdirix** [comment] 2023-10-31 09:35
As we can't reproduce the issue anymore, I'll close it for now. Feel free to reopen if the issue still occurs.

**Closed by sdirix** 2023-10-31 09:35 UTC
Labels: bug
