### ISSUE TITLE
Fix array control (might be already fixed)

### ISSUE THREAD

**Issue by pancho111203** [eclipsesource/jsonforms#282] opened 2016-06-29 13:11 UTC
Added array elements are shown as white boxes

**Comment by edgarmueller** [comment] 2016-06-29 13:12
This was probably already fixed in 0.0.20. Re-check if that's really the case.

**Comment by eneufeld** [comment] 2016-06-29 14:42
I can't reproduce this with the current master, I would close this for now and recommend to reopen it with steps to reproduce if it is still reproducible

**Closed by eneufeld** 2016-06-29 14:42 UTC
Labels: bug
