### ISSUE TITLE
issues with vitejs

### ISSUE THREAD

**Issue by Felix-Staud** [eclipsesource/jsonforms#1744] opened 2021-04-29 21:31 UTC
**Describe the bug**
When trying to use jsonforms with [vitejs/vite](https://github.com/vitejs/vite)

**To Reproduce**
1. try to run a project including jsonforms with [vitejs/vite](https://github.com/vitejs/vite)

**Expected behavior**
Render my page with the given schema/uischema.

**Screenshots**
![image](https://user-images.githubusercontent.com/50131232/116621032-e469b280-a942-11eb-9a11-214ef6e67fa5.png)
![image](https://user-images.githubusercontent.com/50131232/116621055-e895d000-a942-11eb-8613-812171eb89a1.png)

**Browser (please complete the following information):**
 - Chrome (up to date)

**Used Setup (please complete the following information):**
 - Framework: vuejs
 - RendererSet: super-simple barebone custom ones

**Additional context**
This seems to be an issue connected to the `<JsonForms/>` component. 
As long as I don't import that one it works

**Comment by Felix-Puetz** [comment] 2021-04-30 06:55
## Woraround
I found a workaround solution for now but I don't know if this will cause any side effects:
```ts
// vite.config.ts
export default defineConfig({
  plugins: [vue()],
  define: {
    'process.env': process.env,
    'global': {}
  }
});
```

**Comment by sdirix** [comment] 2021-04-30 13:49
Can you check the content of `url.js` where `process` is accessed? This is probably the `url` dependency of `@jsonforms/core`, however as far as I can see `process` is never called in its source file. So probably something goes wrong during transpiling / bundling.

**Comment by sdirix** [comment] 2021-06-24 07:49
With JSON Forms `3.0.0-alpha.0` Vitejs and JSON Forms now work almost completely out of the box. The only manual action still required is to install the `tslib` dependency. However we also plan to fix that for the full JSON Forms 3.0 release.

**Comment by Felix-Puetz** [comment] 2021-06-25 14:43
@sdirix so just a simple `npm i tslib`?

**Comment by sdirix** [comment] 2021-06-25 14:48
yes

**Comment by Druelik** [comment] 2022-04-11 18:52
I migrated my building process to vitejs. While doing so i encountered a bug, which does not render custom renderer. 

Using Jsonforms in dev enviroment works fine and everything is working as expected. 

But if i build my app with vite for production , jsonforms stops rendering any components and doesn't log any error.  Using the vue2-vanilla renderer works fine aswell as if you register the components manually first via the options api.

I made an reproduction repo if you want to take a look. 
https://github.com/Druelik/jsonforms-custom-renderer-vite
npm run dev -> everything working as expected.
npm run build and afterwards npm run serve to preview -> does not render anything and doesnt log any error message.

For me it looks like the components in the renderers are not getting registered/compiled and vue doesn't resolve them correctly.

**Comment by emily-malone** [comment] 2022-08-17 16:07
@Druelik did you find a fix for this?

**Comment by bishopandco** [comment] 2022-08-29 16:44
I am stuck too. In production I can see the VerticalLayouts rendering but all of the inputs are just  html comments.

**Comment by emily-malone** [comment] 2022-08-29 17:21
@bishopandco adding "rollup-plugin-cleanup" worked for me

**Comment by bishopandco** [comment] 2022-08-29 22:16
Thanks @emily-malone, can you expand on your setup? did you add any additional configuration?

**Comment by bart-jaskulski** [comment] 2022-08-31 15:03
@bishopandco I've been stuck with this problem as well.
The issue lies in vite's tree-shaking. If your component looks like those presented in `vue-vanilla` package, then vite has trouble to find out what whether your component was actually used or not. It's a bit larger trouble, I guess (as you have false-positives using jsonforms, which holds renderer component in variable, but this component is not registered).

Anyway, I've found two ways to work it out.
First, not recommended, you can register your component globally, in main file. Yet, I guess it's not really necessary to have it registered - direct import is crucial for vite to know about your dependency.
What I did was to split renderer entry (`renderer + tester`) from component file. My SFC file takes care of display, and in another, shared file I create definition of all renderers entries. This way those are imported, thus correctly resolved by vite.

Let me know, if you need more explanation and some code example perhaps.

**Comment by bishopandco** [comment] 2022-08-31 19:50
@bart-jaskulski thanks. I managed to get it all working by creating a brand new app, installing jsonforms first, and then building up from there. After seeing @sdirix's comment that it's working out of the box ... i went back to the box.  

We are splitting our renderers up like that as well. Like this: https://github.com/eclipsesource/jsonforms-vue-seed/issues/13

**Comment by sdirix** [comment] 2022-09-01 08:27
There is a lot of discussion here but if I understand correctly then there is no actual issue with JSON Forms, right? Or did I miss something and there is something which could be improved?

**Comment by bart-jaskulski** [comment] 2022-09-01 10:08
Hi @sdirix!

I think it more likely Vite issue, as imports from external package are working correctly. I don't event think that DispatchRenderer could work better to somehow inform users about possible issue, because that component receives renderers correctly.

Nevertheless, I would be nice to put information about known bug in documentation with possible workarounds, as it can save a few hours and unpleasant surprise when switching to production environment.

I'll post issue on Vite's board later this week, linking to this issue.

**Comment by sdirix** [comment] 2022-11-08 21:39
I'll close this issue for now. Feel free to reopen if you disagree.

**Closed by sdirix** 2022-11-08 21:39 UTC
Labels: bug, vue

**Comment by cesardddp** [comment] 2024-04-08 19:25
> @bishopandco I've been stuck with this problem as well. The issue lies in vite's tree-shaking. If your component looks like those presented in `vue-vanilla` package, then vite has trouble to find out what whether your component was actually used or not. It's a bit larger trouble, I guess (as you have false-positives using jsonforms, which holds renderer component in variable, but this component is not registered).
> 
> Anyway, I've found two ways to work it out. First, not recommended, you can register your component globally, in main file. Yet, I guess it's not really necessary to have it registered - direct import is crucial for vite to know about your dependency. What I did was to split renderer entry (`renderer + tester`) from component file. My SFC file takes care of display, and in another, shared file I create definition of all renderers entries. This way those are imported, thus correctly resolved by vite.
> 
> Let me know, if you need more explanation and some code example perhaps.

Hi, can i have examples? i make my renders from vue-vanila repo and now im stuck in this issue

**Comment by sdirix** [comment] 2024-04-09 08:56
HI @cesardddp,

Remove the `entry` and `tester` export ".vue" files and only export the renderer there. Then construct the tester and renderer in some other regular Javascript/Typescript file and use that in JSON Forms. That should fix the issue for you.
