### ISSUE TITLE
improve React depth to avoid "Maximum update depth exceeded"

### ISSUE THREAD

**Issue by gilbdev** [eclipsesource/jsonforms#1456] opened 2019-07-24 11:59 UTC
**Describe the bug**
when using nested json structure, i encounter the "Maximum update depth exceeded" really fast.

**To Reproduce**
here is a simplified schema that displays the error (i got soem more comlpex stuff with $ref and so on, but i've tride to make it as simple as possible. a 'oneOf' nested into an 'allOf' doesn(t seem overkill :p

```
{
  "type": "object",
  "allOf": [
    {
      "title": "Main",
      "type": "object",
      "properties": {
        "Name": { "type": "string" }
      },
      "required": [ "Name" ]
    },
    {
      "oneOf": [
        {
          "title": "Flow1",
          "type": "object",
          "properties": {
            "Label": { "type": "string" }
          },
          "required": [ "Label" ]
        },
        {
          "title": "Flow2",
          "type": "object",
          "properties": {
            "Test": { "type": "integer" }
          },
          "required": [ "Test" ]
        }
      ]
    }
  ]
}

```

```
{
    "type": "VerticalLayout",
    "elements": [
      {
        "type": "Control",
        "scope": "#"
      }
     ]
  }
```
kicking one level won't generate the error (btu will change output of json structure with '0' and '1' sections:
```
{
    "type": "VerticalLayout",
    "elements": [
      {
        "type": "Control",
        "scope": "#/allOf/0"
      },
	        {
        "type": "Control",
        "scope": "#/allOf/1"
      }
     ]
  }

```

**Comment by gilbdev** [comment] 2019-07-24 12:02
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

invariant
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:57
scheduleWork
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:20921
enqueueSetState
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:11596
WithWidth.push../node_modules/react/cjs/react.development.js.Component.setState
D:/ExternalCode/jsonforms-react-seed/node_modules/react/cjs/react.development.js:336
WithWidth.componentDidMount
D:/ExternalCode/jsonforms-react-seed/node_modules/@jsonforms/material-renderers/node_modules/@material-ui/core/withWidth/withWidth.js:115
commitLifeCycles
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:18115
commitAllLifeCycles
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:19674
HTMLUnknownElement.callCallback
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:147
invokeGuardedCallbackDev
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:196
invokeGuardedCallback
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:250
commitRoot
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:19898
(anonymous function)
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:21446
unstable_runWithPriority
D:/ExternalCode/jsonforms-react-seed/node_modules/scheduler/cjs/scheduler.development.js:255
completeRoot
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:21445
performWorkOnRoot
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:21368
performWork
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:21273
performSyncWork
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:21247
requestWork
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:21102
scheduleWork
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:20915
scheduleRootUpdate
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:21610
updateContainerAtExpirationTime
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:21636
updateContainer
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:21704
ReactRoot.push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:22017
(anonymous function)
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:22169
unbatchedUpdates
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:21492
legacyRenderSubtreeIntoContainer
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:22165
render
D:/ExternalCode/jsonforms-react-seed/node_modules/react-dom/cjs/react-dom.development.js:22240

```

**Comment by Lily418** [comment] 2019-07-24 17:38
Hi @gilbdev which version of JsonForms are you using? There's some template for reporting bugs.

**Browser (please complete the following information):**
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Used Setup (please complete the following information):**
 - Framework: [e.g. react, angular]
 - RendererSet: [e.g. material, vanilla]

I'm also seeing this issue, but hadn't seen it in previous versions. I'll need to do some investigation to find out when it started appearing.

**Comment by Lily418** [comment] 2019-07-24 17:59
Have reproduced this using just this Schema and no UISchema

```
{
  "type": "object",
  "allOf": [
    {
      "title": "Main",
      "type": "object",
      "properties": {
        "name": { "type": "string" }
      }
    }
  ]
}
```

using master branch of `eclipsesource/jsonforms-react-seed`

**Comment by Lily418** [comment] 2019-07-24 18:06
Hi @gilbdev looks like your issue is you don't need to specify 

`"type": "object" ` when using `allOf`

Try this schema instead (Removed the top level type property)
```
{
  "allOf": [
    {
      "title": "Main",
      "type": "object",
      "properties": {
        "Name": { "type": "string" }
      },
      "required": [ "Name" ]
    },
    {
      "oneOf": [
        {
          "title": "Flow1",
          "type": "object",
          "properties": {
            "Label": { "type": "string" }
          },
          "required": [ "Label" ]
        },
        {
          "title": "Flow2",
          "type": "object",
          "properties": {
            "Test": { "type": "integer" }
          },
          "required": [ "Test" ]
        }
      ]
    }
  ]
}
```

**Comment by edgarmueller** [comment] 2019-07-24 20:48
I think both examples are already fixed with 2.3.x (not 100% sure though, we'll need to re-test). One problem with 2.2.x was that the object renderer and the allOf renderer had the same specificity, so that the object renderer was picked although it was not the right one. We'll update the seed to 2.3.x soon, so you'll be able to retry.

That said, I believe this error could in theory still occur if for some reason the allOf renderer is not available. We'll probably should make this a bit more robust and improve the error reporting.

**Comment by AlexandraBuzila** [comment] 2019-11-21 16:52
Closing this as fixed. I tested this with versions 2.3.1 and  2.3.2-alpha.0 and I can't reproduce the problem anymore.

**Closed by AlexandraBuzila** 2019-11-21 16:52 UTC
Labels: est-2

**Comment by sdirix** [comment] 2019-11-21 16:56
@AlexandraBuzila thanks for checking!

@gilbdev If you still encounter problems feel free to reopen this ticket with more information
