### ISSUE TITLE
Unable to use recursive schema

### ISSUE THREAD

**Issue by jondoe1337** [eclipsesource/jsonforms#1491] opened 2019-08-28 14:24 UTC
**Describe the bug**
I have a json schema which uses a `$ref` as a items reference: https://pastebin.com/EJBLXZ3b (line 57)
After including it in the example and running it: I see in the dev console of my chrome:

```
index.js:42 Uncaught TypeError: Converting circular structure to JSON
    at stringify (index.js:42)
    at stringify (index.js:50)
    at stringify (index.js:50)
    at stringify (index.js:50)
    at stringify (index.js:50)
    at stringify (index.js:50)
    at stringify (index.js:50)
    at stringify (index.js:50)
    at stringify (index.js:50)
````

When I remove line 57 in the schema, it works. 

**To Reproduce**
1. Use React without redux example and use the schema shown above
2. Start example
3. Open dev console

**Expected behavior**
A schema with recursion should work, or at least not fail to be used.

**Browser:**
 - Chrome
 - 76.0.3809.100 (OSX 64bit)

**Used Setup:**
 - Framework: react + express
 - RendererSet: material

**Comment by Lily418** [comment] 2019-08-28 14:40
Hi @jondoe1337 

This is a related issue
https://github.com/eclipsesource/jsonforms/issues/1476

and some discussion about cyclic refs.
https://github.com/eclipsesource/jsonforms/pull/1474#issuecomment-522529303

Also which version of JSON Forms are you using? I think this error is caused by a change introduced in #1474 but that's not included in latest stable release v2.3.0

**Comment by jondoe1337** [comment] 2019-08-28 14:46
Hi @Lily418 sorry for overseeing those issues.

I use v2.3.1

**Comment by Lily418** [comment] 2019-08-28 14:49
I'd try v2.3.0 to avoid that error, but be aware of Stefan's comment https://github.com/eclipsesource/jsonforms/pull/1474#issuecomment-522529303 this may be an issue depending on your use case.

**Comment by sdirix** [comment] 2019-08-28 16:37
The non-redux version of the react-seed partially works for me with your schema when, ironically, the ref parser is configured in the redux store with ```{
    refParserOptions: {
      dereference: {
        circular: "ignore"
      }
    }
  }``` as the last argument of the `init` action.

There seems to be some unintended interaction between the examples in the seed. Also the standalone version seems to hiccup on some of the nested objects while the redux version has no problems there.

We'll need to investigate the behavior of our example seed and how JSON Forms behaves with your schema in a pure non-redux app. Note that you can also pass the refParser options to the `JsonForms` component when needed, although it seems to worsen the behavior in the seed app.

**Comment by sdirix** [comment] 2022-11-08 21:55
This should be fixed with the updates we did to ref-resolving for JSON Forms 3.0. Feel free to reopen in case this error still occurs.

**Closed by sdirix** 2022-11-08 21:55 UTC
Labels: bug, react
