### ISSUE TITLE
Use the Material UI "required" prop

### ISSUE THREAD

**Issue by stevenmckinnon** [eclipsesource/jsonforms#1695] opened 2021-02-16 16:31 UTC
**Is your feature request related to a problem? Please describe.**
When marking a field as required, it only adds the asterisk to the label text rather than using the required prop in InputLabel, which doesn't add the separate `<span />` Material UI renders. Therefore the styling can't be overridden (i.e. style it as red by default). 

**Describe the solution you'd like**
Use InputLabels's required prop

**Describe for which setup you like to have the improvement**
Framework: React
RendererSet: material

**Additional context**
[https://material-ui.com/api/input-label/#props:~:text=FormControl.-,required](https://material-ui.com/api/input-label/#props:~:text=FormControl.-,required)

**Comment by sdirix** [comment] 2021-02-17 06:57
Good idea!

**Comment by sdirix** [comment] 2021-02-17 16:27
Duplicate of https://github.com/eclipsesource/jsonforms/issues/1390

**Comment by sdirix** [comment] 2021-02-17 16:40
Actually it's not really a duplicate. The other issue specifically mentions `if/then/else` which is much harder than a general support of the `required` prop.

**Closed** 2021-09-13 14:16 UTC
Labels: enhancement, react, material, good first issue
