### ISSUE TITLE
Allow customizing the validation approach

### ISSUE THREAD

**Issue by Morriz** [eclipsesource/jsonforms#1567] opened 2020-03-30 10:23 UTC
When an empty form is required, we provide no data to the form (`undefined`), which renders an empty form just fine. However, the onChange handler reports errors (probably because `undefined` is not dealt with properly).
When we provide an empty object to `data` (`{}`) the onChange handler does not report this error anymore, but now we see validation errors immediately, even though the form is not dirty.

IMO: user input should be triggering field validation when no initial value is provided, or when it is provided but with invalid value.

Are you using dirty flags to disable initial form field validation? Otherwise, I suggest you do.

**Comment by sdirix** [comment] 2020-04-02 08:25
At the moment we don't directly support this use case. The validation errors are computed initially and on every data change and are used unconditionally.

There are many different use cases for "delayed" validation. Once could do it initially, like we do at the moment, only in some cases initially like you suggested, only on a user edit or on batch at the end triggered by an user action. Also there are complications regarding for example nested objects: are they considered dirty once one of their fields are updated or only when all of them were.

Once we have a clean concept for this I would be happy to introduce a customizable validation process to JSON Forms. Note that we would like to [restructure the validation anyway](https://github.com/eclipsesource/jsonforms/issues/1557), to also allow JSON Forms in general to work without the Ajv dependency and giving more control to the user.

There are some approaches you could take at the moment to implement the desired behavior:
- Implement custom renderers which only show the errors once you would like them to show. You could mostly wrap existing renderers and modify their `errors` prop for this.
- Use the `setErrors` action whenever the errors change to set your own errors. Here you can filter all errors you don't want to show at the moment. [This is easier in Redux than in the standalone component at the moment](https://spectrum.chat/jsonforms/general/how-do-i-config-styles-or-classes-i-want-to-use-for-controls-or-forms~fd68a632-f9d1-480f-a2bc-235c2223691a)
 - You could also wrap Ajv with your own customized variant and filter all errors you don't want to see this way. As your wrapped variant will be called each time data has changed you can effectively implement some of the mentioned use cases.
 - In general you can exchange the reducers used and implement your logic there.

I hope this helps ;)

**Comment by sdirix** [comment] 2020-04-02 08:31
> When an empty form is required, we provide no data to the form (`undefined`), which renders an empty form just fine. However, the onChange handler reports errors (probably because `undefined` is not dealt with properly).

I created a [new issue](https://github.com/eclipsesource/jsonforms/issues/1570) for this. Thanks for the report!

**Comment by Morriz** [comment] 2020-04-02 11:38
Sure. For now we moved to this solution which provides saner defaults. Maybe you could look into it: https://github.com/rjsf-team/react-jsonschema-form

**Comment by sdirix** [comment] 2020-07-13 13:25
Duplicate of https://github.com/eclipsesource/jsonforms/issues/1535

**Closed by sdirix** 2020-07-13 13:25 UTC
Labels: feature, react
