### ISSUE TITLE
Conditions should be composable

### ISSUE THREAD

**Issue by pragnesh-is** [eclipsesource/jsonforms#1141] opened 2018-11-04 19:44 UTC
1) How can I implement not equal condition ?
2) In case my property is array, how can I check that array contains some value or not ?

**Comment by edgarmueller** [comment] 2018-11-06 19:53
I think this has been partly answered in https://github.com/eclipsesource/jsonforms-react-seed/issues/24 already (the `schema` property is just a regular JSON schema), but to address you two specific questions

1. Use [const](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.3) or an [enum](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.2) with just a single value
2. Use [contains](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.4.6)

Hope this helps, if not, feel free to re-open.

**Comment by pragnesh-is** [comment] 2018-11-07 18:57
In ui schema, how to check OR conditions against two different scopes ?, I want to show one property only if any one of two condition matched, those two conditions are like property1 contains "something" OR property2 contains "something"

**Comment by edgarmueller** [comment] 2018-11-09 15:30
Use the `schema` condition with [`oneOf`](https://json-schema.org/understanding-json-schema/reference/combining.html) which should enable what you ask for.

**Comment by pragnesh-is** [comment] 2018-11-10 04:11
> I think this has been partly answered in [eclipsesource/jsonforms-react-seed#24](https://github.com/eclipsesource/jsonforms-react-seed/issues/24) already (the `schema` property is just a regular JSON schema), but to address you two specific questions
> 
> 1. Use [const](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.3) or an [enum](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.2) with just a single value
> 2. Use [contains](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.4.6)
> 
> Hope this helps, if not, feel free to re-open.

If you have observer I does not wants to check two conditions against same property, I wants to check two conditions against two different property. I have tried to use oneOf at rule level and condition level but  its not working. I am adding both code here.

Sample1:
```
{
    "type": "VerticalLayout",
    "elements": [
        {
            "type": "Control",
            "label": false,
            "scope": "#/properties/done"
        },
        {
            "type": "Control",
            "scope": "#/properties/name"
        },
        {
            "type": "Control",
            "scope": "#/properties/comments"
        },
        {
            "type": "HorizontalLayout",
            "elements": [
                {
                    "type": "Control",
                    "scope": "#/properties/due_date"
                },
                {
                    "type": "Control",
                    "scope": "#/properties/rating"
                }
            ]
        },
        {
            "type": "Control",
            "scope": "#/properties/description",
            "options": {
                "multi": true
            }
        },
        {
            "type": "HorizontalLayout",
            "elements": [
                {
                    "type": "Control",
                    "scope": "#/properties/recurrence"
                },
                {
                    "type": "Control",
                    "scope": "#/properties/recurrence_interval",
                    "rule": {
                        "effect": "SHOW",
                        "condition": {
                            "oneOf": [
                                {
                                    "scope": "#/properties/name",
                                    "schema": { "enum": ["testName"] }
                                },
                                {
                                    "scope": "#/properties/description",
                                    "schema": { "enum": ["testDescription"] }
                                }
                            ]
                        }
                    }
                }
            ]
        }
    ]
}
```

Sample2: 
```
{
    "type": "VerticalLayout",
    "elements": [
        {
            "type": "Control",
            "label": false,
            "scope": "#/properties/done"
        },
        {
            "type": "Control",
            "scope": "#/properties/name"
        },
        {
            "type": "Control",
            "scope": "#/properties/comments"
        },
        {
            "type": "HorizontalLayout",
            "elements": [
                {
                    "type": "Control",
                    "scope": "#/properties/due_date"
                },
                {
                    "type": "Control",
                    "scope": "#/properties/rating"
                }
            ]
        },
        {
            "type": "Control",
            "scope": "#/properties/description",
            "options": {
                "multi": true
            }
        },
        {
            "type": "HorizontalLayout",
            "elements": [
                {
                    "type": "Control",
                    "scope": "#/properties/recurrence"
                },
                {
                    "type": "Control",
                    "scope": "#/properties/recurrence_interval",
                    "oneOf": [
                        {
                            "rule": {
                                "effect": "SHOW",
                                "condition": {
                                    "scope": "#/properties/name",
                                    "schema": { "enum": ["testName"] }
                                }
                            }
                        },
                        {
                            "rule": {
                                "effect": "SHOW",
                                "condition": {
                                    "scope": "#/properties/name",
                                    "schema": { "enum": ["testName"] }
                                }
                            }
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by edgarmueller** [comment] 2018-11-12 15:54
Ah, I see, now I understand what you are trying to do. Unfortunately these types of conditions aren't supported yet, but we'll add support for them soon.

**Comment by edgarmueller** [comment] 2019-01-08 13:30
PR #1206 available. Feedback welcome

**Comment by eneufeld** [comment] 2019-01-09 16:56
Closed via #1206

**Closed by eneufeld** 2019-01-09 16:56 UTC
Labels: core

**Comment by sque89** [comment] 2022-11-03 16:26
Hi @edgarmueller, sorry to comment here again but it appeared to me to be best fitting. I want to do exactly the same as the issue creator highlighted:

having a rule for a Control, which has two conditions against two different properties. I am trying this but it does not work and i cannot find any documentation of an example:

`{
          "type": "Control",
          "scope": "#/properties/cif",
          "rule": {
            "effect": "HIDE",
            "condition": {
              "allOf": [
                {
                  "scope": "#/properties/amount",
                  "schema": { "exclusiveMaximum": 100 }
                },
                {
                  "scope": "#/properties/company",
                  "schema": { "const": true }
                }
              ]
            }
          }
        }`

Help would be very much appreciated. Thanks!

**Comment by eneufeld** [comment] 2022-11-04 11:33
Hi @sque89 ,
you can always use the [discourse group](https://jsonforms.discourse.group/) for questions like this.

About your question. 
What you can do is, move the allOf down.
So you would have 1 condition pointing the scope to the root schema, and a schema which does the checks.
so something like this:
```
{
  "type": "Control",
  "scope": "#/properties/cif",
  "rule": {
    "effect": "HIDE",
    "condition": {
      "scope": "#",
      "schema": {
        "properties": {
          "amount": {
            "exclusiveMaximum": 100
          },
          "company": {
            "const": true
          }
        }
      }
    }
  }
}
```

**Comment by sque89** [comment] 2022-11-04 11:57
Hi @eneufeld, that is a great tip, i will do so in case of future questions. For now i continue here if you dont mind.

I tried your suggestion and it works but in this case it is considered to be an "OR" operation. So either on of it needs to be true to trigger the effect.

But what i need is an AND operation, so both constraints need to be true to trigger the effect. How can i achieve that?

**Comment by eneufeld** [comment] 2022-11-04 12:35
What you want is that both properties are mandatory/required.
So your schema should look like this:
```
{
  "properties": {
    "amount": {
      "exclusiveMaximum": 100
    },
      "company": {
        "const": true
      }
  },
  "required":["amount", "company"]        
}
```

**Comment by sque89** [comment] 2022-11-04 13:10
Sorry if i am not explaining it well enough. No i don't need to have the two properties mandatory, or at least it is not relevant for my use case.

I need to base the visibility of one field on the value of two other fields:

only show the field **cif** if **amount > 100 AND company == true**

**Comment by eneufeld** [comment] 2022-11-04 13:15
that should work with the schema provided, because if one of the props is missing the schema will provide validation errors.
What is wrong in the schema though, is the `exclusiveMaximum` as is checks that the amount is `<100`. You need to use `exclusiveMinimum` to get `>100` .

**Comment by sque89** [comment] 2022-11-04 13:24
Ok i see you are right the logic is already AND. Now i am using this rule which generally works. But now the problem is, that the field is initially visible. Only if i toggle one of the fields then it gets hidden. So i assume i need to use the HIDE effect, but then i need an OR condition between both properties. How can achieve that?

```
"rule": {
  "effect": "SHOW",
  "condition": {
    "scope": "#",
    "schema": {
      "properties": {
        "amountCustom": {
          "exclusiveMinimum": 100
        },
        "company": {
          "const": true
        }
      }
    }
  }
}
```

**Comment by eneufeld** [comment] 2022-11-04 13:33
you lost me ;-) .
So you want the field to only be visible when the amount>100 and company===true ?
if so your schema would be correct besides missing the `required` property
to achieve an or, remove the required property from above, as this will ignore empty fields. you can also use anyOf as the root in the schema section and group 2 separate schemas to get a cleaner or behavior

**Comment by sque89** [comment] 2022-11-04 14:01
Awesome, using anyOf in the scheme worked just fine. Thanks a lot for your support!
