### ISSUE TITLE
Preselect with default schema values

### ISSUE THREAD

**Issue by johnmorrell** [eclipsesource/jsonforms#1193] opened 2018-12-13 10:56 UTC
For enumerated properties presented as a drop down list, where a default value is specified in the schema, it would make sense to pre-select that value. For example, 'red' should be pre selected:

```
      "colours":{
         "type":"string",
         "enum":[
            "red",
            "green",
            "blue"
         ],
         "default":"red"
      }
```

**Comment by edgarmueller** [comment] 2019-01-23 15:02
@johnmorrell We have made changes that allow options to be passed in into the `createAjv` function. This enables us to use the `useDefaults: true` option, which should cover your use case (it's probably best if you take a look at the changes in #1224). Please let us know whether this solves your issue. This change will be part of the 2.2.0 release.

**Comment by edgarmueller** [comment] 2019-01-23 15:14
Please re-open if you experience any issues.

**Comment by johnmorrell** [comment] 2019-01-25 00:20
Thank you @edgarmueller, I have taken a look at this in v2.1.1-alpha.3

I can see that this is working for regular string types, but it does not appear to support the case where the string is of an enum type, eg:

```
"colours":{
  "type":"string",
    "enum":[
      "red",
      "green",
      "blue"
  ],
   "default":"red"
}
```

**Comment by johnmorrell** [comment] 2019-01-25 00:43
There is also an unusual behaviour when a default is set for basic strings (react/material).

If you select the field and try to delete the value, it deletes up to the last character then the default value returns. This is also the case if you select all of the text and attempt to delete.

**Comment by edgarmueller** [comment] 2019-01-25 19:21
Thanks for the update. We'll look into it again.

**Comment by AlexandraBuzila** [comment] 2019-02-22 11:56
@johnmorrell I just had a look at references and defaults. This is indeed not working and it seems to be a limitation of ajv: https://github.com/epoberezkin/ajv/issues/337#issuecomment-308864772

One way of working around this would be to add a default alongside your reference:

```javascript
{
   "type":"object",
   "properties":{
      "color":{
         "type":"string",
         "enum":[
            "red",
            "green",
            "blue"
         ],
         "default":"green"
      },
      "referencedColor":{
         "$ref":"#/definitions/referencedColor",
         "default":"blue"
      }
   },
   "definitions":{
      "referencedColor":{
         "type":"string",
         "enum":[
            "red",
            "green",
            "blue"
         ],
         "default":"green"
      }
   }
}
```

**Comment by johnmorrell** [comment] 2019-02-25 09:46
Thanks @AlexandraBuzila. I understand the issue now, and thanks for the workaround.

**Comment by marshallmcdonnell** [comment] 2019-05-01 19:46
I'm trying to do the same as the original post (display default values for enum). Yet, setting up a `jsonforms-react-seed` to replicate this example for `color` does not have the pre-selection. 

My repo to try and reproduce this is: 
https://github.com/marshallmcdonnell/jsonforms-react-default-test

Schema JSON for the colors with default value: 
https://github.com/marshallmcdonnell/jsonforms-react-default-test/blob/master/src/schema.json

UI Schema JSON:
https://github.com/marshallmcdonnell/jsonforms-react-default-test/blob/master/src/uischema.json

Deployment on GitHub Pages to see that the form doesn't auto-populate with "green":
https://marshallmcdonnell.github.io/jsonforms-react-default-test/

I must be missing something. Apologies in advance, new to JSONForms, React, and JavaScript.

JSONForms version: 2.2.3

**Comment by edgarmueller** [comment] 2019-05-03 10:21
@marshallmcdonnell Sorry for late reply: JSON Forms utilizies ajv to set defaults, so you need to create a custom instance and hand it in. In the `src/index.tsx` file, update the `init` action call to the following:

```javascript
const ajv = createAjv({
  useDefaults: true
})
store.dispatch(Actions.init(data, schema, uischema, ajv));
```

**Comment by marshallmcdonnell** [comment] 2019-05-03 12:05
@edgarmueller Awesome, thanks! I'll try that out.

**Comment by marshallmcdonnell** [comment] 2019-05-03 12:12
That did it, much appreciated!

**Comment by eneufeld** [comment] 2019-06-29 07:14
@edgarmueller I suggest to close this due to f515b143bb7e384e9e505717f5c9e1bea8870ee6 , what do you think?

**Comment by edgarmueller** [comment] 2019-07-01 15:31
@eneufeld  Sounds good to me! Closing.

**Closed by edgarmueller** 2019-07-01 15:31 UTC
Labels: material, react
