### ISSUE TITLE
Exporting "pure", non-HOC wrapped elements

### ISSUE THREAD

**Issue by mcsonka-exscientia** [eclipsesource/jsonforms#2054] opened 2022-11-24 16:34 UTC
### Is your feature request related to a problem? Please describe.

I would like to wrap some components, in my specific example the `MaterialAnyOfRenderer` to format the labels/add some conditional elements. For that I will need to import the component without the `withJsonFormsAnyOfProps` wrapper. Unfortunately that's not exported from the library.

### Describe the solution you'd like

I would like the "pure" components - ones without the `withJsonForms<something>Props` wrappers exported from the library.

### Describe alternatives you've considered

As the environment I'm working in is using Typescript, I was trying to import it directly, but unfortunately that's not an option because of tsconfig/babel setups which cannot be changed.

### Framework

Core, React

### RendererSet

Material

**Comment by sdirix** [comment] 2022-12-15 15:58
This is a duplicate of https://github.com/eclipsesource/jsonforms/issues/1687

We're aware of the issue and we want to tackle it in the intermediate future, hence the current `3.x` milestone. If you would like to contribute this fix, please feel free to do so!

**Closed by sdirix** 2022-12-15 15:58 UTC
Labels: duplicate
