### ISSUE TITLE
Really slow React performance with category + nested array with many items

### ISSUE THREAD

**Issue by georgiosd** [eclipsesource/jsonforms#1641] opened 2020-09-22 10:36 UTC
The object itself is not that complex, but it has a nested array with about 100 short string:

```
{
 prop1: ...,
 prop2: ...,
 dict: {
  A: [...array of strings],
  B: [...array of strings],
  C: [...array of strings]
 }
}
```

Changing one of the strings value causes a ton of re-renders in, presumably, the array editor:

<img width="659" alt="Screenshot 2020-09-22 at 1 10 07 PM" src="https://user-images.githubusercontent.com/1672054/93872256-8c960980-fcd8-11ea-920a-fe2b7e3481e7.png">

This is on latest stable: 2.4.0 with material-ui renderers

**Comment by georgiosd** [comment] 2020-09-22 10:42
EDIT: the issue persists in 2.4.1-beta.0

**Comment by sdirix** [comment] 2020-09-22 11:16
Hi @georgiosd, thanks for the report. Looking at your screenshot it seems like we construct new callback functions, e.g. `moveUp` and `moveDown` for each row in each render call. Because of this our default `React.memo` is failing to cache the result for the unchanged rows and they are rerendered. Checking the code [confirms this suspicion] (https://github.com/eclipsesource/jsonforms/blob/83a4dd26be88eaa3733d1a1f128f11c31a968cf5/packages/material/src/complex/MaterialTableControl.tsx#L361-L362).

To fix this we either need to customize the props check in `React.memo` or make sure to only construct these functions when necessary, i.e. use `useCallback`. In general I would prefer the latter approach.

**Comment by georgiosd** [comment] 2020-09-22 12:16
@sdirix that would make sense to me also - if you promise to publish a new beta after the fix, I can send a pull request :)

**Comment by sdirix** [comment] 2020-09-22 12:43
If the PR meets our standards, is relatively small, straightforward to understand and fixes this issue I would be willing to add it to this release (i.e. publish a new beta). If the PR itself is fine but it turned out that more things had to be changed and therefore the PR feels "risky", then I would add it to the first alpha of the next release instead.

So I won't promise you a new beta. It depends purely on the PR and whether we correctly identified the issue whether we can make it part of the release so late in the cycle (release is this month) or not. In any way, ff the PR is fine it will be part of some released JSON Forms pretty soon (beta this release or alpha next release).

**Comment by georgiosd** [comment] 2020-09-22 13:14
@sdirix of course the PR will have to pass your "tests" also, I wasn't expecting a free ride so to speak. 

I asked for that because I'm about to deliver a new project and this is gonna cause some complaints from the client so a hotfix release would be appreciated.

Do you know if there is an easy way to keep the project locally and load it in my project instead of the npm registry copy?

**Comment by sdirix** [comment] 2020-09-22 13:38
I can recommend [yalc](https://github.com/whitecolor/yalc). That's what we use to test packages locally, for example to test new JSON Forms versions in the seed repository.

**Comment by georgiosd** [comment] 2020-09-22 14:32
Thank you @sdirix .

I'm also seeing another problem... I've created a custom control which I'm successfully matching to multiple locations.

What I'm seeing is that the memo will block a re-render of the control when it's rendered for another scope. 

Any pointers?

**Comment by sdirix** [comment] 2020-09-22 14:40
Hmm I'm not sure whether the memo is responsible for this as each rendered control is an own instance. The memo just avoids rerendering a specific instance when none of its props changed and doesn't sync multiple instances. You can easily see this with the provided renderer set as for example all text inputs will match to the same renderer, i.e. the same renderer also matches on multiple controls.

I would have to look at your custom renderer to determine what the problem is.

**Comment by georgiosd** [comment] 2020-09-22 14:43
This is it... thank you for the fast responses!

```
import { rankWith, scopeEndIs } from '@jsonforms/core'
import { withJsonFormsControlProps } from '@jsonforms/react'
import {
    Card,
    CardActions,
    CardContent,
    CardHeader,
    makeStyles
} from '@material-ui/core'
import { Alert } from '@material-ui/lab'
import { Api } from 'freebottles-web'
import React from 'react'
import { useDropzone } from 'react-dropzone'
import { useMutation } from 'react-query'
import { ProgressButton } from 'zmvp-nextjs/material-ui'

function ImageUrlEditor({ id, data, handleChange, path, label, description }) {
    const [imageUrl, setImageUrl] = React.useState(data)
    const [error, setError] = React.useState(null)

   ...

    React.useEffect(() => {
        setImageUrl(data)
    }, [data])

    const { ref, ...rootProps } = getRootProps()
    const classes = useStyles()
    return (
        <Card>
            <CardHeader title={label} subheader={description} />
            <CardContent>
                {error ? (
                    <Alert severity="error">
                        The current image URL cannot be loaded
                    </Alert>
                ) : (
                    <img
                        src={imageUrl}
                        alt={label}
                        onError={() => setError(true)}
                        className={classes.media}
                    />
                )}
            </CardContent>
            <CardActions>
                <div ref={ref} {...rootProps}>
                    <input {...getInputProps()} />
                    <ProgressButton
                        isLoading={isLoading}
                        size="small"
                        color="secondary"
                    >
                        Change
                    </ProgressButton>
                </div>
            </CardActions>
        </Card>
    )
}

export default {
    tester: rankWith(3, scopeEndIs('imageUrl')),
    renderer: withJsonFormsControlProps(ImageUrlEditor)
}
```

**Comment by georgiosd** [comment] 2020-09-22 14:46
I think I fixed this one, thank you. 

I will see if I can improve on the rendering and let you know

**Comment by sdirix** [comment] 2020-11-21 12:48
Closing this for now. Please reopen when you have further problems :)

**Closed by sdirix** 2020-11-21 12:48 UTC
Labels: bug, material, react
