### ISSUE TITLE
Angular 12 compatibility

### ISSUE THREAD

**Issue by StefanSchoof** [eclipsesource/jsonforms#1761] opened 2021-06-10 09:49 UTC
**Describe the bug**

**To Reproduce**
1. `git clone https://github.com/eclipsesource/jsonforms-angular-seed.git`
2. `cd jsonforms-angular-seed`
3. `ng update @angular/core@12 @angular/cli@12`
4. get error: "Package "@jsonforms/angular-material" has an incompatible peer dependency to "zone.js" (requires "^0.10.2", would install "0.11.4").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later."
5. `ng update @angular/core@12 @angular/cli@12 --force` (works without an error)
6. `npm start`
7. Get the error:
```./node_modules/json-schema-ref-parser/lib/resolvers/http.js:3:13-28 - Error: Module not found: Error: Can't resolve 'http' in 'C:\Users\SSchoof\source\github\jsonforms-angular-seed\node_modules\json-schema-ref-parser\lib\resolvers'
Did you mean './http'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (C:/Users/SSchoof/source/github/jsonforms-angular-seed, node_modules). 
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory 
too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }

./node_modules/json-schema-ref-parser/lib/resolvers/http.js:4:14-30 - Error: Module not found: Error: Can't resolve 'https' in 'C:\Users\SSchoof\source\github\jsonforms-angular-seed\node_modules\json-schema-ref-parser\lib\resolvers'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
        - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "https": false }
```

**Expected behavior**
jsonforms is working with latest released angular version

**Screenshots**
n/a

**Browser (please complete the following information):**
n/a

**Used Setup (please complete the following information):**
 - Framework: angular
 - RendererSet: material

**Additional context**

**Comment by StefanSchoof** [comment] 2021-06-14 12:18
Hi @sdirix,

I saw you created #1762, which resolves the webpack 5 problem, but it looks like a braking change. Since I currently evaluate my options, to integrate jsonforms in a existing Angular 12 app, can you please give me any info about the plans for releasing this change. Should this be part of the 3.0 release? If so, do you plan to put prereleases on npm soon?

**Comment by sdirix** [comment] 2021-06-14 12:39
Hi @StefanSchoof, first, thank you for the report. As you noticed, the cause of the reported issue lies in the `json-schema-ref-parser` which we want to remove with #1750.

#1762 should fix the error presented here. While it's a (minor) breaking change, it's only one for the React Material renderers. The Angular renderers never used this functionality anyway. So besides the error going away, you shouldn't notice any difference.

For the final 3.0 release we plan to integrate more changes. However as soon as #1762 is merged we'll definitely do an 3.0 alpha prerelease which can be consumed by you.

**Comment by StefanSchoof** [comment] 2021-06-14 14:28
Thanks, @sdirix for the quick explanation. Then I will try to get my forms to fly.

**Closed** 2021-06-16 13:05 UTC
Labels: angular, bug, core

**Comment by sdirix** [comment] 2021-06-24 09:01
Hi @StefanSchoof, JSON Forms 3.0.0-alpha.0 is now released containing the removal of the json-schema-ref-parser. You can consume it by referring to the concrete version or simply use the next tag, for example npm install @jsonforms/core@next @jsonforms/react@next @jsonforms/material-renderers@next.

**Comment by StefanSchoof** [comment] 2021-07-02 10:59
Thanks, I found today time to look into it and it is working.
