### ISSUE TITLE
Complete Rendering fails when no renderer is found for one UI schema element

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#267] opened 2016-05-20 08:55 UTC
The rendering should be more graceful and log the error (e.g. into the DOM as comment) but continue rendering

**Comment by eneufeld** [comment] 2016-06-16 10:55
@koegel isn't this a duplicate of #199 ?

**Comment by koegel** [comment] 2016-06-17 16:52
Not really, this is about complete rendering failure, the other one is
about reporting errors properly imho

On Thu, Jun 16, 2016 at 12:55 PM, Eugen Neufeld <notifications@github.com>
wrote:

> @koegel <https://github.com/koegel> isn't this a duplicate of #199
> <https://github.com/eclipsesource/jsonforms/issues/199> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eclipsesource/jsonforms/issues/267#issuecomment-226452965>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA_xtOAWHmPbaKbOO7XonW_BvtdhG85_ks5qMSuPgaJpZM4IjASu>
> .
>



-- 

Dr. Maximilian Koegel

Senior Software Architect / General Manager
EclipseSource Munich

Email: mkoegel@eclipsesource.com
Web: http://eclipsesource.com/munich
Mobil: +49 176 223 619 18
Phone: +49 89 21 555 30 - 10
Fax: +49 89 21 555 30 - 19
Skype: maximilian.koegel
Hangouts: mkoegel@eclipsesource.com

EclipseSource Muenchen GmbH
Agnes-Pockels-Bogen 1
80992 München

General Managers: Dr. Jonas Helming, Dr. Maximilian Koegel
Registered Office: Agnes-Pockels-Bogen 1, 80992 Muenchen,
Commercial Register München, HRB 191789

**Comment by eneufeld** [comment] 2016-06-18 19:23
Ok, I see. 
But then this is invalid, as this does not happen with the current master because of a bug in the rendererservice a renderer is always returned, and this one can fail then during rendering.
The result is, that in a horizontal layout an empty space is left, as the div is there but has no content.
I would close this one and move #199 to the 0.0.30 milestone.
Would you agree?

**Closed** 2016-06-24 13:12 UTC
Labels: P2
