### ISSUE TITLE
Date Picker doesn't work on mobile devices with material-renderers `v3.2.1`

### ISSUE THREAD

**Issue by MikeyZat** [eclipsesource/jsonforms#2299] opened 2024-03-12 10:05 UTC
### Describe the bug

Date Picker does not work on mobile (touch) devices, the date dialog never opens dialog. On desktop it works, however, sometimes on the very 1st click nothing happens (you have to click twice to open the dialog). It used to be working in `v3.1.0`. I think it might be related to [this commit](https://github.com/eclipsesource/jsonforms/commit/01b08f0e3441f82848c1c4917c3f21b9a8d74e5d#diff-15be6988b9d1abddcdfbedb6676d57962bf6f0a78ae8d089dd9fe95a4f0ac8b5).

### Expected behavior

When touching the date picker on mobile device, I should see the date dialog open.

### Steps to reproduce the issue

1. Go to https://jsonforms-react-seed.netlify.app/
2. Either select mobile device in chrome dev tools or use physical mobile device
3. Click on the date picker
4. Nothing happens

### Screenshots

https://github.com/eclipsesource/jsonforms/assets/41756225/cc382202-e0ad-4b35-b3d9-8fd392155d00

### Which Version of JSON Forms are you using?

v3.2.1

### Framework

React

### RendererSet

Material

### Additional context

Related thread: https://jsonforms.discourse.group/t/how-to-use-date-input-on-mobile/1951

On the official MUI demo page, it works good: https://mui.com/x/react-date-pickers/getting-started/#render-your-first-component

I've tried updating the `@mui/x-date-pickers` to latest version, or even to 7.0.0-beta.6 but it didn't help. It must be related to some custom renderer code that wraps the date picker.

**Comment by LukasBoll** [comment] 2024-04-16 11:04
Hi, 
thank you for the report! This should be fixed in the latest prerelease 3.3.0-alpha.1
Duplicate of #2278

**Comment by lucas-koehler** [comment] 2024-04-16 11:14
@MikeyZat I'm closing this now as it should be fixed already. If the problem persists with version `3.3.0-alpha.1` or later feel free to reopen this.

**Closed by lucas-koehler** 2024-04-16 11:14 UTC
Labels: bug, react, material
