### ISSUE TITLE
Need convention based approach to be easy and scalable 

### ISSUE THREAD

**Issue by mmcedora** [eclipsesource/jsonforms#1633] opened 2020-08-31 08:41 UTC
**Is your feature request related to a problem? Please describe.**
The current GUI models are to verbose for simple things. The benefit of jsonforms almost disappear when one have to explicitly name and define each gui control in the GUI model. It is very expensive to maintain a large amount of forms if each form needs an explicit gui model.

JsonForms should be able to draw default gui based on (preferably configurable) conventions just like every when web framework for the last 10 year has done since Ruby On Rails.

**Describe the solution you'd like**
Use a convention over configuration approach, where configuration is only necessary when overriding default behavior.

**Comment by eneufeld** [comment] 2020-08-31 09:09
Hi @mmcedora , 
thank you for your suggestion.

JSONForms already allows you to not pass in a uischema if a simply vertical layout of all properties in the order they appear in the schema is enough.

Could you elaborate which conventions you would expect besides this one?

**Comment by mmcedora** [comment] 2020-08-31 09:36
So it is all or nothing if I understand jsonforms correctly? However, if I replace the gui model with just {} in the seed project file, it does not render anything. I would expect that I could attach an empty gui model or a part gui model that only specifics the parts that override generic behavior. 

P.S. I also found "https://jsonform.github.io/jsonform/playground/index.html?example=schema-basic" which is capable of rendering nicely without any uischema. It use sensible defaults and looks quite nice. I haven't looked at how flexible it is, but if it can be customized that would be more interesting for me because the gui model is not needed unless in special cases.

**Comment by eneufeld** [comment] 2020-08-31 10:05
The problem with supporting partial gui models is that the framework can't know whether the fields were missed by mistake or on purpose.
So if you provide a ui schema, the framework renders whatever is defined there.Thus an empty object is interpreted as a provided schema (I agree this is quite harsh). An `undefined` ui schema is interpreted as no schema being provided and thus it will be generated.
If you want to support a partial model in your application you can do it. The `generateUISchema` method is exposed. You could write some code which takes your partial model and merges it with the generated one e voila.

**Comment by mmcedora** [comment] 2020-08-31 10:26
I think, the rule for if unconfigured fields should be shown with a default UI or not is a bool setting (e.g. default convention) that the user could specify.

I think this jsonforms project has a lot of potential but the current harsh configuration approach is simply too much work. See (here)[https://en.wikipedia.org/wiki/Convention_over_configuration] for a description of how to deal with this in principle.

**Comment by eneufeld** [comment] 2020-08-31 10:31
Thank you for the link. We are aware of the concept. The problem is always to find a balance. 
As JSONForms is an OpenSource Project, we are always happy to accepts contributions.
I suggest to close this issue as it is too generic to be handled.
Please feel free to open more precise feature requests with a description how a convention should work so less configuration is needed. Feel free to reopen this issue if you disagree.

**Closed by eneufeld** 2020-08-31 10:31 UTC
