### ISSUE TITLE
Is "dot-separated" path safe?

### ISSUE THREAD

**Issue by mirismaili** [eclipsesource/jsonforms#1849] opened 2021-12-11 11:45 UTC
### Describe the bug

As you know there is a `path` prop that is passed to the renderer that indicates the location of `data` (that should be rendered by that renderer) in the root `data` object (e.g. `'foo.bar'`).

It's a **dot-separated string**:

https://github.com/eclipsesource/jsonforms/blob/81f1f19dac49b1864e712e9abbc5c5c6355a2b91/packages/core/src/util/path.ts#L82-L90

```js
compose(path, segments.join('.'))
```

_**Is this safe? Then `'foo.bar'` points to `data.foo.bar` or `data['foo.bar']`?**_

### Expected behavior

The library should can distinguish between these paths. For example, using arrays (instead of strings):
```js
path1 = ['foo', 'bar']
path2 = ['foo.bar']
```

### Steps to reproduce the issue

 1. Go to [Playground](https://mirismaili.github.io/jsonforms-playground)
 
2. Set:
    `JSON-Schema`:
    ```json
    {
      "type": "object",
      "properties": {
        "my.name": {
          "type": "string"
        }
      }
    }
    ```
    `UI-Schema`:
    ```json
    false
    ```
    `Data`:
    ```json
    {
      "my.name": "S. Mahdi",
      "my": {
        "name": "MirIsmaili"
      }
    }
    ```

As you can see in the [playground](https://mirismaili.github.io/jsonforms-playground/?hideinfo), the synchronization process flows along with **the green arrows** (see below screenshot), but NOT along with **the red arrows**. _(When you edit the form, `data['my.name']` will be updated (only) and when you edit `data.my.name` in the editor (only), the form will be updated)._

### Screenshots

![image](https://user-images.githubusercontent.com/15800189/145674684-4b53db88-2031-4e0e-9f65-4bb8ae348c95.png)

### In which browser are you experiencing the issue?

Google Chrome v96.0.4664.93 (Official Build) (64-bit)

**Comment by sdirix** [comment] 2021-12-13 08:02
Hi @mirismaili, thanks for the report. The issue is [already reported](https://github.com/eclipsesource/jsonforms/issues/1631) and we're already on a fix, see #1831. However the change is non trivial as using an array as a prop triggers rerenders by default in all bindings. Therefore we want to make sure that we don't introduce any regressions.

**Comment by mirismaili** [comment] 2021-12-14 13:04
Hi @sdirix, 

OK. So I develop new features that I'm working on ([additionalProperties](http://json-schema.org/understanding-json-schema/reference/object.html#additional-properties) and [patternProperties](http://json-schema.org/understanding-json-schema/reference/object.html#pattern-properties)), _with this issue_ until this be resolved.

**Comment by sdirix** [comment] 2023-06-29 11:39
We settled on an improvement, documented it in https://github.com/eclipsesource/jsonforms/issues/2153 and will start developing it soon. Therefore I'll close this issue as the follow up already exists.

**Closed by sdirix** 2023-06-29 11:39 UTC
Labels: bug, core
